### ISSUE TITLE
UUID Not generated when using in widget area

### ISSUE THREAD

**Issue by marcusorjames** [philbuchanan/Accordion-Blocks#152]
I am using this plugin in order to create expandable filters in a woocommerce sidebar. Unfortunately the UUID doesn't seem to be generating and is outputting as `NaN` for the  ids.

I tested this in a regular block on a page and it works fine, so must be my use of it in the widget area.

I am using PHP7.3 and Wordpress 5.8.1

**Comment by marcusorjames** [comment]
Hi thank you for your quick resolution of this, however I am still experiencing the same bug. 

Plugin updated and hard refreshed. Also tried to create new accordions, same problem :(

**Comment by philbuchanan** [comment]
@marcusorjames You may need to recreate existing accordion items in order for a new ID to be generated.

**Comment by marcusorjames** [comment]
Yeh I tried that, also tried it in a new widget location incase the existing ones were causing an issue. Still getting NaN.

I have triple checked the plugin is updated.
![accordian-blocks-NaN](https://user-images.githubusercontent.com/853845/143042123-4168d718-1cb9-4166-9f9c-c1bed1daf437.png)

**Comment by spencerfinnell** [comment]
Hey @philbuchanan, thanks for the great plugin. I am experiencing the same issue while using the plugin with Full Site Editing. 

According to [the documentation, `select()` will always return an `object`](https://github.com/WordPress/gutenberg/blob/trunk/packages/data/README.md#select), not `null`. This causes the following condition to ultimately return `null` because [`getCurrentPostId()`](https://github.com/WordPress/gutenberg/blob/26c8b7149091a315a0da09544cc74cfdc5fbd9c3/docs/reference-guides/data/data-core-editor.md#getcurrentpostid) _can_ return `null`. 

https://github.com/philbuchanan/Accordion-Blocks/blob/ecee6ddb1b49d73daf1410458480b4e0402cd01a/src/block/edit.js#L82-L85

`Number( null + 123 )` results in the reported `NaN`.

I believe the following will be more flexible in different editing environments:

```js
const entityId = useSelect((select) => {
	return select("core/editor").getCurrentPostId() ?? 0;
});
```
